dist: bionic
language: python
python:
- 3.8
cache: pip
script:
- bash scripts/travis.sh
before_deploy:
- bash scripts/travis-release-hooks.sh BEFORE
deploy:
- skip_cleanup: false
  api_key: $GITHUB_PAT
  draft: true
  provider: releases
  on:
    branch: master
    tags: true
after_deploy:
- bash scripts/travis-release-hooks.sh AFTER
