dist: trusty
language: bash
branches:
    only:
        - master
script:
      - echo "Logging in as ${DOCKER_USER}"
      - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - docker build -t approova .
      - docker images
      - docker tag approova $DOCKER_USER/approova
      - docker push $DOCKER_USER/approova
