apiVersion: apps/v1
kind: Deployment
metadata:
  name: approova-live
spec:
  replicas: 1
  selector:
    matchLabels:
      name: approova-live
  template:
    metadata:
      labels:
        name: approova-live
    spec:
      volumes:
        - name: approova-live-content
          persistentVolumeClaim:
            claimName: approova-live-pvc
      restartPolicy: Always
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      containers:
        - name: approova-live
          image: alex4108/approova:GIT_SHA
          volumeMounts:
            - mountPath: "/content"
              name: approova-live-content
          env:
            - name: APPROOVA_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: approova-live-discord
                  key: password
