apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      name: DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        name: DEPLOYMENT_NAME
    spec:
      restartPolicy: Always
      containers:
      - name: DEPLOYMENT_NAME
        image: DOCKER_USER/approova:COMMIT
        env:
        - name: ENV
          value: "ENVIRONMENT"
        - name: APPROOVA_DISCORD_TOKEN
          valueFrom:
          secretKeyRef:
            name: approova-environment-discord
            key: password
        - name: RUN_TESTS
          value: "0"   
      volumeMounts:
        - mountPath: "/content"
          name: approova-environment-nfs
      imagePullSecrets:
      - name: approova-environment-docker