# This only needs to before the first approova deployment to the cluster.
# All you should need to change is NFS_HOST and NFS_PATH
apiVersion: v1
kind: PersistentVolume
metadata:
  name: approova-live-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_HOST
    path: "NFS_PATH"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: approova-test-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_HOST
    path: "NFS_PATH"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: approova-live-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: approova-live-pv
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: approova-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: approova-test-pv
  resources:
    requests:
      storage: 100Mi


