# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Approova Docs
email: alex4108@live.com
description: |
  Documentation for the Approova Discord Bot
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://approova.github.io" # the base hostname & protocol for your site
github_username: alex4108

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
gems: [jekyll-paginate]
plugins:
  - jemoji
