name: Tests

permissions: "read-all"

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run golang compilation check
        run: make build
      - name: Build docker image
        run: make docker
