name: Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run golang tests
      run: make test
    - name: Build docker image
      run: make docker
